openapi: '3.1.0'
info:
  title: Board-inference
  version: '1.0'
servers:
  - url: https://localhost:50003/

paths:
  /classify:
    post:
      parameters:
        - name: model
          in: query
          required: false
          schema:
            type: string
            enum: [albert, heliumbert]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClassifyRequestDTO"

      responses:
        "200":
          description: "Classification result"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassifyResponseDTO"

  /contentExtract:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required: [file]
      
      responses:
        "200":
          description: "Content Extract Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentExtractDTO"

  /documentInfer:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
              required: [files]
      responses:
        '200':
          description: "Document Inference Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentInferFieldsDTO"


components:
  schemas:
    Label:
      type: string
      enum:
        - LETTER
        - FORM
        - EMAIL
        - HANDWRITTEN
        - ADVERTISEMENT
        - SCIENTIFIC_REPORT
        - SCIENTIFIC_PUBLICATION
        - SPECIFICATION
        - FILE_FOLDER
        - NEWS_ARTICLE
        - BUDGET
        - INVOICE
        - PRESENTATION
        - QUESTIONNAIRE
        - RESUME
        - MEMO

    ClassifyRequestDTO:
      type: object
      properties:
        text:
          type: string
      required: [text]

    LabelProbabilityDTO:
      type: object
      properties:
        label:
          $ref: "#/components/schemas/Label"
        probability:
          type: number
      required: [label, probability]

    ClassifyResponseDTO:
      type: object
      properties:
        labelProbabilities:
          type: array
          items:
            $ref: "#/components/schemas/LabelProbabilityDTO"
        loss:
          type: number
        time_s:
          type: number
        suggestedLabels:
          type: array
          items:
            $ref: "#/components/schemas/Label"
      required: [labelProbabilities, loss, time_s, suggestedLabels]


    ContentExtractDTO:
      type: object
      properties:
        content:
          type: string
      required: [content]

    DocumentInferFieldsDTO:
      type: object
      properties:
        content:
          type: string
        title:
          type: [string, "null"]
        description:
          type: string
        documentNumber:
          type: [string, "null"]
        officeName:
          type: [string, "null"]
        documentDate:
          type: [string, "null"]
        notes:
          type: [string, "null"]
        classifyResponse:
          $ref: "#/components/schemas/ClassifyResponseDTO"
      required: [content, title, description, documentNumber, officeName, documentDate, notes, classifyResponse]
