/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Base"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentMany"];
        put?: never;
        post: operations["DocumentCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentGet"];
        put?: never;
        post?: never;
        delete: operations["DocumentSoftDelete"];
        options?: never;
        head?: never;
        patch: operations["DocumentUpdate"];
        trace?: never;
    };
    "/api/documents/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DocumentRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DocumentHardDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/auditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentAuditLogGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DocumentFileCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentFileGet"];
        put?: never;
        post?: never;
        delete: operations["DocumentFileSoftDelete"];
        options?: never;
        head?: never;
        patch: operations["DocumentFileUpdate"];
        trace?: never;
    };
    "/api/documents/{id}/files/{fileId}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentFileContentGet"];
        put?: never;
        post: operations["DocumentFileBlobPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/files/{fileId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DocumentFileRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/files/{fileId}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DocumentFileHardDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/files/{fileId}/auditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DocumentFileAuditLogGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserMany"];
        put?: never;
        post: operations["UserCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserGet"];
        put?: never;
        post?: never;
        delete: operations["UserSoftDelete"];
        options?: never;
        head?: never;
        patch: operations["UserUpdate"];
        trace?: never;
    };
    "/api/users/{id}/auditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserAuditLogGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserDeleteSelf"];
        options?: never;
        head?: never;
        patch: operations["UserUpdateSelf"];
        trace?: never;
    };
    "/api/users/current/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserPasswordUpdateSelf"];
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionGetSelf"];
        put?: never;
        post?: never;
        delete: operations["SessionDeleteSelf"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/auditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionAuditLogGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Classify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/contentExtract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentExtract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/documentInfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DocumentInfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    actorId?: components["schemas"]["id"];
                    entityId?: components["schemas"]["id"];
                    entityType?: "DOCUMENT" | "DOCUMENT_FILE" | "USER" | "SESSION";
                    logActions?: components["parameters"]["LogActionsQuery"];
                    fromDate?: components["parameters"]["FromDateQuery"];
                    toDate?: components["parameters"]["ToDateQuery"];
                    pageSize?: components["parameters"]["PageSizeQuery"];
                    cursor?: components["parameters"]["CursorQuery"];
                    sortOrder?: components["parameters"]["SortOrderQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogResponseDTO"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fromDate?: components["parameters"]["FromDateQuery"];
                    toDate?: components["parameters"]["ToDateQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponseDTO"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: date-time */
        date: string;
        /** Format: uuid */
        id: string;
        anything: Record<string, never> | unknown[] | boolean | number | string | null;
        /** @enum {string} */
        DocumentClassification: "OFFICIAL" | "CONFIDENTIAL";
        /** @enum {string} */
        DocumentReceiveMode: "EMAIL" | "HAND_CARRY" | "COURIER" | "OTHER";
        /** @enum {string} */
        DocumentFileLabel: "LETTER" | "FORM" | "EMAIL" | "HANDWRITTEN" | "ADVERTISEMENT" | "SCIENTIFIC_REPORT" | "SCIENTIFIC_PUBLICATION" | "SPECIFICATION" | "FILE_FOLDER" | "NEWS_ARTICLE" | "BUDGET" | "INVOICE" | "PRESENTATION" | "QUESTIONNAIRE" | "RESUME" | "MEMO";
        /** @enum {string} */
        UserPrivilege: "ADMIN" | "BASIC";
        /** @enum {string} */
        LogAction: "CREATE" | "READ" | "UPDATE" | "DELETE" | "SOFT_DELETE" | "RESTORE";
        ErrorDTO: {
            message: string;
            moreInfo?: components["schemas"]["anything"];
        };
        ActorDTO: {
            id: components["schemas"]["id"];
            username: string;
        };
        DocumentCreateDTO: {
            title: string;
            description?: string;
            documentDate: components["schemas"]["date"];
            documentNumber: string;
            classification: components["schemas"]["DocumentClassification"];
            receiveMode: components["schemas"]["DocumentReceiveMode"];
            officeName: string;
            notes?: string;
        };
        DocumentUpdateDTO: {
            title?: string;
            description?: string;
            documentDate?: components["schemas"]["date"];
            documentNumber?: string;
            classification?: components["schemas"]["DocumentClassification"];
            receiveMode?: components["schemas"]["DocumentReceiveMode"];
            officeName?: string;
            notes?: string;
        };
        DocumentResponseDTO: {
            id: components["schemas"]["id"];
            title: string;
            description?: string;
            documentDate: components["schemas"]["date"];
            documentNumber?: string;
            classification: components["schemas"]["DocumentClassification"];
            receiveMode: components["schemas"]["DocumentReceiveMode"];
            officeName: string;
            notes?: string;
            createdAt: components["schemas"]["date"];
            updatedAt: components["schemas"]["date"];
            author: components["schemas"]["ActorDTO"];
            updator: components["schemas"]["ActorDTO"];
            files: components["schemas"]["DocumentFileResponseDTO"][];
            softDeletedAt?: components["schemas"]["date"] | null;
        };
        DocumentManyResponseItemDTO: {
            id: components["schemas"]["id"];
            title: string;
            description?: string;
            documentDate: components["schemas"]["date"];
            documentNumber?: string;
            classification: components["schemas"]["DocumentClassification"];
            receiveMode: components["schemas"]["DocumentReceiveMode"];
            officeName: string;
            notes?: string;
            createdAt: components["schemas"]["date"];
            updatedAt: components["schemas"]["date"];
            author: components["schemas"]["ActorDTO"];
            updator: components["schemas"]["ActorDTO"];
            softDeletedAt?: components["schemas"]["date"] | null;
        };
        DocumentManyResponseDTO: {
            list: components["schemas"]["DocumentManyResponseItemDTO"][];
            nextCursor: components["schemas"]["id"] | null;
        };
        DocumentSoftDeleteActionResponseDTO: {
            id: components["schemas"]["id"];
            title: string;
        };
        DocumentHardDeleteResponseDTO: {
            id: components["schemas"]["id"];
            title: string;
            failedDeleteFiles: {
                id: components["schemas"]["id"];
                error: string;
            }[];
        };
        DocumentFileCreateDTO: {
            title: string;
            content: string;
            labels?: components["schemas"]["DocumentFileLabel"][];
        };
        DocumentFileUpdateDTO: {
            title?: string;
            content?: string;
            labels?: components["schemas"]["DocumentFileLabel"][];
        };
        DocumentFileCreateResponseDTO: {
            id: components["schemas"]["id"];
            createdAt: components["schemas"]["date"];
            uploadFileTo: string;
        };
        DocumentFileResponseDTO: {
            id: components["schemas"]["id"];
            documentId: components["schemas"]["id"];
            title: string;
            content: string;
            labels: components["schemas"]["DocumentFileLabel"][];
            mimetype: string;
            fileSizeBytes: number;
            createdAt: components["schemas"]["date"];
            updatedAt: components["schemas"]["date"];
            author: components["schemas"]["ActorDTO"];
            updator: components["schemas"]["ActorDTO"];
            softDeletedAt?: components["schemas"]["date"] | null;
        };
        DocumentFileStatusChangeResponseDTO: {
            id: components["schemas"]["id"];
            documentId: components["schemas"]["id"];
            title?: string;
        };
        UserCreateDTO: {
            username: string;
            email: string;
            password: string;
            privilege: components["schemas"]["UserPrivilege"];
        };
        UserUpdateOtherDTO: {
            username?: string;
            email?: string;
            privilege?: components["schemas"]["UserPrivilege"];
        };
        UserUpdateSelfDTO: {
            username?: string;
            email?: string;
        };
        UserPasswordUpdateSelfDTO: {
            currentPassword: string;
            newPassword: string;
        };
        UserResponseDTO: {
            id: components["schemas"]["id"];
            username: string;
            email: string;
            privilege: components["schemas"]["UserPrivilege"];
            createdAt: components["schemas"]["date"];
            updatedAt: components["schemas"]["date"];
            deletedAt: components["schemas"]["date"] | null;
        };
        UserManyResponseDTO: {
            list: {
                id: components["schemas"]["id"];
                username: string;
                email: string;
                privilege: components["schemas"]["UserPrivilege"];
                createdAt: components["schemas"]["date"];
                updatedAt: components["schemas"]["date"];
                deletedAt: components["schemas"]["date"] | null;
            }[];
            nextCursor: components["schemas"]["id"] | null;
        };
        UserDeleteResponseDTO: {
            id: components["schemas"]["id"];
            username: string;
            deletedAt: components["schemas"]["date"];
        };
        SessionCreateDTO: {
            username: string;
            password: string;
        };
        SessionFindResponseDTO: {
            user: {
                id: components["schemas"]["id"];
                username: string;
                email: string;
                privilege: components["schemas"]["UserPrivilege"];
            };
        };
        SessionDeleteResponseDTO: {
            user: {
                id: components["schemas"]["id"];
                username: string;
            };
        };
        /** @enum {string} */
        ClassifyLabel: "LETTER" | "FORM" | "EMAIL" | "HANDWRITTEN" | "ADVERTISEMENT" | "SCIENTIFIC_REPORT" | "SCIENTIFIC_PUBLICATION" | "SPECIFICATION" | "FILE_FOLDER" | "NEWS_ARTICLE" | "BUDGET" | "INVOICE" | "PRESENTATION" | "QUESTIONNAIRE" | "RESUME" | "MEMO";
        ClassifyRequestDTO: {
            text: string;
        };
        ClassifyLabelProbabilityDTO: {
            label: components["schemas"]["ClassifyLabel"];
            probability: number;
        };
        ClassifyResponseDTO: {
            labelProbabilities: components["schemas"]["ClassifyLabelProbabilityDTO"][];
            loss: number;
            time_s: number;
            suggestedLabels: components["schemas"]["ClassifyLabel"][];
        };
        ContentExtractResponseDTO: {
            content: string;
        };
        DocumentInferFieldsDTO: {
            content: string;
            title: string | null;
            description: string;
            documentNumber: string | null;
            officeName: string | null;
            documentDate: components["schemas"]["date"] | null;
            notes: string | null;
            classifyResponse: components["schemas"]["ClassifyResponseDTO"];
        };
        AuditLogResponseDTO: {
            list: {
                id: components["schemas"]["id"];
                action: components["schemas"]["LogAction"];
                actor: {
                    id: components["schemas"]["id"];
                    username: string;
                };
                createdAt: components["schemas"]["date"];
                documentLog?: {
                    document?: {
                        id: components["schemas"]["id"];
                        title: string;
                    };
                    documentIdSnapshot: components["schemas"]["id"];
                    documentTitleSnapshot: string;
                };
                documentFileLog?: {
                    document?: {
                        id: components["schemas"]["id"];
                        title: string;
                    };
                    documentIdSnapshot: components["schemas"]["id"];
                    documentTitleSnapshot: string;
                    documentFile?: {
                        id: components["schemas"]["id"];
                        title: string;
                    };
                    documentFileIdSnapshot: components["schemas"]["id"];
                    documentFileTitleSnapshot: string;
                };
                userLog?: {
                    user?: {
                        id: components["schemas"]["id"];
                        username: string;
                    };
                    userIdSnapshot: components["schemas"]["id"];
                    userNameSnapshot: string;
                };
                sessionLog?: {
                    user?: {
                        id: components["schemas"]["id"];
                        username: string;
                    };
                    userIdSnapshot: components["schemas"]["id"];
                    userNameSnapshot: string;
                };
            }[];
            nextCursor: components["schemas"]["id"] | null;
        };
        DashboardResponseDTO: {
            documents: {
                count: number;
                softDeletedCount?: number;
                recentActivity: components["schemas"]["DocumentManyResponseItemDTO"][];
                noFileDocuments: components["schemas"]["DocumentManyResponseItemDTO"][];
                activity: {
                    date: components["schemas"]["date"];
                    createCount: number;
                }[];
            };
            file: {
                count: number;
                softDeletedCount?: number;
                totalUsedStorageBytes: number;
                labelGraph: {
                    label: components["schemas"]["DocumentFileLabel"];
                    count: number;
                }[];
            };
            auditLogs?: {
                activity: {
                    date: components["schemas"]["date"];
                    createCount: number;
                    readCount: number;
                    updateCount: number;
                    deleteCount: number;
                    softDeleteCount: number;
                    restoreCount: number;
                }[];
            };
        };
    };
    responses: {
        /** @description Client does not have sufficient permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDTO"];
            };
        };
        /** @description Client tried to find a resource that doesn't exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDTO"];
            };
        };
        /** @description Client is not authorized for this request. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDTO"];
            };
        };
        /** @description Client sent a malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDTO"];
            };
        };
        /** @description Client sent a request with conflicting information. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDTO"];
            };
        };
        /** @description An internal server error occurred. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["anything"];
            };
        };
    };
    parameters: {
        SearchTermQuery: string;
        FromDateQuery: components["schemas"]["date"];
        ToDateQuery: components["schemas"]["date"];
        AuthorQuery: components["schemas"]["id"];
        DocumentClassificationQuery: components["schemas"]["DocumentClassification"];
        DocumentReceiveModeQuery: components["schemas"]["DocumentReceiveMode"];
        DocumentFileLabelsQuery: components["schemas"]["DocumentFileLabel"][];
        ShowSoftDeletedQuery: boolean;
        DocumentSortByQuery: "TITLE" | "DOCUMENT_DATE" | "DOCUMENT_NUMBER" | "OFFICE_NAME" | "CREATED_AT" | "UPDATED_AT";
        LogActionsQuery: components["schemas"]["LogAction"][];
        PageSizeQuery: number;
        CursorQuery: components["schemas"]["id"];
        SortOrderQuery: "ASC" | "DESC";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Base: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    DocumentMany: {
        parameters: {
            query?: {
                searchTerm?: components["parameters"]["SearchTermQuery"];
                fromDate?: components["parameters"]["FromDateQuery"];
                toDate?: components["parameters"]["ToDateQuery"];
                classification?: components["parameters"]["DocumentClassificationQuery"];
                receiveMode?: components["parameters"]["DocumentReceiveModeQuery"];
                fileLabels?: components["parameters"]["DocumentFileLabelsQuery"];
                authorId?: components["parameters"]["AuthorQuery"];
                showSoftDeleted?: components["parameters"]["ShowSoftDeletedQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
                documentSortBy?: components["parameters"]["DocumentSortByQuery"];
                sortOrder?: components["parameters"]["SortOrderQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentManyResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentCreateDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentSoftDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSoftDeleteActionResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentUpdateDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentRestore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSoftDeleteActionResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentHardDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentHardDeleteResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentAuditLogGet: {
        parameters: {
            query?: {
                includeFileLogs?: boolean;
                logActions?: components["parameters"]["LogActionsQuery"];
                fromDate?: components["parameters"]["FromDateQuery"];
                toDate?: components["parameters"]["ToDateQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
                sortOrder?: components["parameters"]["SortOrderQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentFileCreateDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileCreateResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileSoftDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileStatusChangeResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentFileUpdateDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileContentGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileBlobPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileRestore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileStatusChangeResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileHardDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentFileStatusChangeResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentFileAuditLogGet: {
        parameters: {
            query?: {
                logActions?: components["parameters"]["LogActionsQuery"];
                fromDate?: components["parameters"]["FromDateQuery"];
                toDate?: components["parameters"]["ToDateQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
                sortOrder?: components["parameters"]["SortOrderQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserMany: {
        parameters: {
            query?: {
                searchTerm?: components["parameters"]["SearchTermQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserManyResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserCreateDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserSoftDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDeleteResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdateOtherDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserAuditLogGet: {
        parameters: {
            query?: {
                logActions?: components["parameters"]["LogActionsQuery"];
                fromDate?: components["parameters"]["FromDateQuery"];
                toDate?: components["parameters"]["ToDateQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
                sortOrder?: components["parameters"]["SortOrderQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserDeleteSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDeleteResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserUpdateSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdateSelfDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UserPasswordUpdateSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserPasswordUpdateSelfDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SessionCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionCreateDTO"];
            };
        };
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SessionGetSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFindResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SessionDeleteSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleteResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SessionAuditLogGet: {
        parameters: {
            query?: {
                userId?: components["schemas"]["id"];
                logActions?: components["parameters"]["LogActionsQuery"];
                fromDate?: components["parameters"]["FromDateQuery"];
                toDate?: components["parameters"]["ToDateQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
                cursor?: components["parameters"]["CursorQuery"];
                sortOrder?: components["parameters"]["SortOrderQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    Classify: {
        parameters: {
            query?: {
                model?: "albert" | "heliumbert";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClassifyRequestDTO"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ContentExtract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentExtractResponseDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DocumentInfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Document Inference Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInferFieldsDTO"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
